version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env:r
    restart: unless-stopped
    networks:
      - my-books-network

  frontend:
    container_name: frontend
    build:
      context: ./src/main/resources/mybooks-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: /api
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - my-books-network

  db:
    image: postgres:15.6-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=mybooks
    volumes:
      - /db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - my-books-network

volumes:
  mongo-data:

networks:
  my-books-network: